apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cha
  namespace: group1-team6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-cha
  template:
    metadata:
      labels:
        app: springboot-cha
    spec:
      containers:
      - name: springboot-cha
        image: k8s-vga-worker1:5000/group1-team6-cha5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: team6-springboot-cha-sv
  namespace: group1-team6
spec:
  selector:
    app: springboot-cha
  ports:
    - protocol: TCP
      port: 8080 # kube unique inner port
      targetPort: 8080 #listen port, container port, Docker Expose port is equal
      nodePort: 30606
  type: NodePort